# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\rama\resource\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(797, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("background-color:transparent")
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.video = QtWidgets.QLabel(self.centralwidget)
        self.video.setGeometry(QtCore.QRect(0, 0, 801, 601))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.video.sizePolicy().hasHeightForWidth())
        self.video.setSizePolicy(sizePolicy)
        self.video.setStyleSheet("background-color: transparent;")
        self.video.setText("")
        self.video.setObjectName("video")
        self.direction = QtWidgets.QTextBrowser(self.centralwidget)
        self.direction.setGeometry(QtCore.QRect(20, 10, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.direction.setFont(font)
        self.direction.setStyleSheet("color:white; border-radius:5;background-color:rgba(82,204,199,0.53)")
        self.direction.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.direction.setFrameShadow(QtWidgets.QFrame.Plain)
        self.direction.setLineWidth(0)
        self.direction.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.direction.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.direction.setObjectName("direction")
        self.rForward = QtWidgets.QLabel(self.centralwidget)
        self.rForward.setGeometry(QtCore.QRect(330, 10, 111, 71))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.rForward.setFont(font)
        self.rForward.setStyleSheet("background-color: rgba(170,170,170,0.37);\n"
"border-radius: 20;\n"
"color : white")
        self.rForward.setAlignment(QtCore.Qt.AlignCenter)
        self.rForward.setObjectName("rForward")
        self.rRight = QtWidgets.QLabel(self.centralwidget)
        self.rRight.setGeometry(QtCore.QRect(670, 280, 111, 71))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.rRight.setFont(font)
        self.rRight.setStyleSheet("background-color: rgba(170,170,170,0.37);\n"
"border-radius: 20;\n"
"color : white")
        self.rRight.setAlignment(QtCore.Qt.AlignCenter)
        self.rRight.setObjectName("rRight")
        self.rBack = QtWidgets.QLabel(self.centralwidget)
        self.rBack.setGeometry(QtCore.QRect(330, 510, 111, 71))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.rBack.setFont(font)
        self.rBack.setStyleSheet("background-color: rgba(170,170,170,0.37);\n"
"border-radius: 20;\n"
"color : white")
        self.rBack.setAlignment(QtCore.Qt.AlignCenter)
        self.rBack.setObjectName("rBack")
        self.rLeft = QtWidgets.QLabel(self.centralwidget)
        self.rLeft.setGeometry(QtCore.QRect(10, 280, 111, 71))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.rLeft.setFont(font)
        self.rLeft.setStyleSheet("background-color: rgba(170,170,170,0.37);\n"
"border-radius: 20;\n"
"color : white")
        self.rLeft.setAlignment(QtCore.Qt.AlignCenter)
        self.rLeft.setObjectName("rLeft")
        self.startVideo = QtWidgets.QPushButton(self.centralwidget)
        self.startVideo.setGeometry(QtCore.QRect(640, 520, 121, 41))
        self.startVideo.setStyleSheet("color:white; border-radius:5;background-color:rgba(82,204,199,0.53)")
        self.startVideo.setObjectName("startVideo")
        self.video.raise_()
        self.rForward.raise_()
        self.direction.raise_()
        self.rRight.raise_()
        self.rBack.raise_()
        self.rLeft.raise_()
        self.startVideo.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.direction.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:20pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\';\">STOP</span></p></body></html>"))
        self.rForward.setText(_translate("MainWindow", "0 CM"))
        self.rRight.setText(_translate("MainWindow", "0 CM"))
        self.rBack.setText(_translate("MainWindow", "0 CM"))
        self.rLeft.setText(_translate("MainWindow", "0 CM"))
        self.startVideo.setText(_translate("MainWindow", "START VIDEO"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
